"""initial schema

Revision ID: 581afeb93402
Revises: 
Create Date: 2026-08-21 17:58:22.761587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# Custom column types referenced by autogenerated migrations.
import src.models.types


# revision identifiers, used by Alembic.
revision: str = '581afeb93402'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('objective', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_at', src.models.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('end_at', src.models.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('budget_type', sa.String(length=16), nullable=False),
    sa.Column('budget_amount_minor', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('spend_cap_minor', sa.BigInteger(), nullable=True),
    sa.Column('pacing', sa.String(length=16), nullable=False),
    sa.Column('send_cap_total', sa.Integer(), nullable=True),
    sa.Column('send_cap_per_day', sa.Integer(), nullable=True),
    sa.Column('frequency_cap_per_recipient', sa.Integer(), nullable=False),
    sa.Column('special_category', sa.String(length=48), nullable=False),
    sa.Column('disclaimer_text', sa.String(length=500), nullable=True),
    sa.Column('utm_source', sa.String(length=80), nullable=True),
    sa.Column('utm_medium', sa.String(length=80), nullable=True),
    sa.Column('utm_campaign', sa.String(length=80), nullable=True),
    sa.Column('utm_content', sa.String(length=80), nullable=True),
    sa.Column('external_ref', sa.String(length=120), nullable=True),
    sa.Column('audience_type', sa.String(length=16), nullable=False),
    sa.Column('published_at', src.models.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('archived_at', src.models.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', src.models.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', src.models.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("budget_type = 'NONE' OR budget_amount_minor IS NOT NULL", name='ck_budget_amount_required'),
    sa.CheckConstraint("special_category = 'NONE' OR disclaimer_text IS NOT NULL", name='ck_disclaimer_required_for_category'),
    sa.CheckConstraint('end_at IS NULL OR start_at IS NULL OR end_at > start_at', name='ck_end_after_start'),
    sa.CheckConstraint('spend_cap_minor IS NULL OR budget_amount_minor IS NULL OR spend_cap_minor >= budget_amount_minor', name='ck_spend_cap_gte_budget'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index('idx_campaign_owner_status_created', ['owner_user_id', 'status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_external_ref'), ['external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_status'), ['status'], unique=False)

    # Alembic's autogenerate does not detect functional indexes, so this one
    # is written explicitly. Without it, campaign-name uniqueness would be
    # unenforced on any database built from migrations. The expression form is
    # valid on both PostgreSQL and SQLite.
    op.execute(
        "CREATE UNIQUE INDEX uniq_campaign_owner_name "
        "ON campaigns (owner_user_id, lower(name))"
    )

    op.create_table('campaign_experiences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('video_url', sa.String(length=2048), nullable=True),
    sa.Column('poster_url', sa.String(length=2048), nullable=True),
    sa.Column('captions_url', sa.String(length=2048), nullable=True),
    sa.Column('video_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('headline', sa.String(length=80), nullable=True),
    sa.Column('personalised_message', sa.Text(), nullable=True),
    sa.Column('created_at', src.models.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', src.models.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_experiences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_experiences_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('campaign_recipients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('customer_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('external_ref', sa.String(length=120), nullable=True),
    sa.Column(
        'attributes',
        # JSONB on Postgres, plain JSON on SQLite.
        sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'),
        nullable=True,
    ),
    sa.Column('created_at', src.models.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', src.models.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_recipients_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index('uniq_recipient_email_per_campaign', ['campaign_id', 'email'], unique=True)

    op.create_table('campaign_options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experience_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('intent', sa.String(length=16), nullable=False),
    sa.Column('follow_up_type', sa.String(length=16), nullable=False),
    sa.Column('follow_up_message', sa.Text(), nullable=True),
    sa.Column('follow_up_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', src.models.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', src.models.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(follow_up_type = 'MESSAGE' AND follow_up_message IS NOT NULL) OR (follow_up_type = 'URL' AND follow_up_url IS NOT NULL) OR (follow_up_message IS NULL AND follow_up_url IS NULL)", name='ck_follow_up_matches_type'),
    sa.CheckConstraint('position IN (1, 2)', name='ck_option_position'),
    sa.ForeignKeyConstraint(['experience_id'], ['campaign_experiences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_options_experience_id'), ['experience_id'], unique=False)
        batch_op.create_index('uniq_option_key', ['experience_id', 'key'], unique=True)
        batch_op.create_index('uniq_option_position', ['experience_id', 'position'], unique=True)

    op.create_table('campaign_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('experience_id', sa.String(length=36), nullable=True),
    sa.Column('recipient_id', sa.String(length=36), nullable=True),
    sa.Column('option_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('occurred_at', src.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.CheckConstraint("(type = 'RESPONSE' AND option_id IS NOT NULL) OR (type = 'VIEW' AND option_id IS NULL)", name='ck_option_required_for_response'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['experience_id'], ['campaign_experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_id'], ['campaign_options.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['campaign_recipients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_events', schema=None) as batch_op:
        batch_op.create_index('idx_events_campaign_type', ['campaign_id', 'type'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_events_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index('uniq_response_per_session', ['campaign_id', 'session_id'], unique=True, sqlite_where=sa.text("type = 'RESPONSE'"), postgresql_where=sa.text("type = 'RESPONSE'"))
        batch_op.create_index('uniq_view_per_session', ['campaign_id', 'session_id'], unique=True, sqlite_where=sa.text("type = 'VIEW'"), postgresql_where=sa.text("type = 'VIEW'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS uniq_campaign_owner_name")
    with op.batch_alter_table('campaign_events', schema=None) as batch_op:
        batch_op.drop_index('uniq_view_per_session', sqlite_where=sa.text("type = 'VIEW'"), postgresql_where=sa.text("type = 'VIEW'"))
        batch_op.drop_index('uniq_response_per_session', sqlite_where=sa.text("type = 'RESPONSE'"), postgresql_where=sa.text("type = 'RESPONSE'"))
        batch_op.drop_index(batch_op.f('ix_campaign_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_campaign_events_campaign_id'))
        batch_op.drop_index('idx_events_campaign_type')

    op.drop_table('campaign_events')
    with op.batch_alter_table('campaign_options', schema=None) as batch_op:
        batch_op.drop_index('uniq_option_position')
        batch_op.drop_index('uniq_option_key')
        batch_op.drop_index(batch_op.f('ix_campaign_options_experience_id'))

    op.drop_table('campaign_options')
    with op.batch_alter_table('campaign_recipients', schema=None) as batch_op:
        batch_op.drop_index('uniq_recipient_email_per_campaign')
        batch_op.drop_index(batch_op.f('ix_campaign_recipients_campaign_id'))

    op.drop_table('campaign_recipients')
    with op.batch_alter_table('campaign_experiences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_experiences_campaign_id'))

    op.drop_table('campaign_experiences')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_campaigns_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_campaigns_external_ref'))
        batch_op.drop_index('idx_campaign_owner_status_created')

    op.drop_table('campaigns')
    # ### end Alembic commands ###
